### ISSUE TITLE
documentation to integrate into graphhopper

### ISSUE THREAD

**Issue by kahidna** [karussell/graphhopper-traffic-data-integration#2]
hi, 
I'm trying to integrate graphhopper-traffic-data-integration into graphhopper on our server.
we run graphhopper as a docker. I tried to add the files into the docker and then run ./td.sh datasource=/path/to/file.pbf inside the docker, and I think it's failed. here is the output : 
```
ls: cannot access 'target/traffic-demo-*-dependencies.jar': No such file or directory
./td.sh: line 10: mvn: command not found
ls: cannot access 'target/traffic-demo-*-dependencies.jar': No such file or directory
Error: Unable to access jarfile datasource=/data/file.pb
```
is there more clear documentation that I can try?

**Comment by karussell** [comment]
It looks like you need to install maven before running the td.sh or deploy the jar in docker instead
